name: Build
on: [ push ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest